### ISSUE TITLE
Pressing a button and sliding off keeps the button held down

### ISSUE THREAD

**Issue by asherao** [wluc9875/iUFCExport-iPad#35]
In addition, the command is sent on button release. So in this case, if I were to press button 1 on the UFC, hold, and slide, then lift over button two, button 1 in the sim will remain depresses. I can get it depressed if I release a tab over button 1 on the iPad. That is when the command seems to be sent to DCS.

**Comment by wluc9875** [comment]
Thanks @asherao!
Yes, this is known missing use-case. Fix will be provided in the next version

**Comment by asherao** [comment]
👍

**Comment by asherao** [comment]
Version 1.1(5)
Behavior has changed and is much better.
-Press and hold on iPad
-Drag finger to a different part of the screen
-iPad animates released button, but DCS button is still held
-Release finger, DCS button releases

**Comment by wluc9875** [comment]
Got it. I only focused on the DCS button release when the finger slides off the button.
I'll look into the difference between iPad and DCS for the held position.

**Comment by wluc9875** [comment]
The last part is going to be a little bit harder to change than expected. I'll open a separate GH issue for this one, to be fixed at a later time and I'll consider this one fixed for version 1.1.
