### ISSUE TITLE
F18 - The "<>" displayed in game when a radio is in use is displayed on the ipad as "d"

### ISSUE THREAD

**Issue by asherao** [wluc9875/iUFCExport-iPad#38]
Steps to repeat the bug:
-Start Free Fly Mission
-Press "\"
-Press "F5" for ATC menu
-Press "F1" to call Batumi
-Press "F1" to call Inbound
-Note the COMM 2 channel window on the iPad changes to "d" during both transmissions instead of the in game symbol that resembles "<>".

**Comment by asherao** [comment]
Version 1.1(5)
-Start Free Fly Mission
-Press ""
-Press "F5" for ATC menu
-Press "F1" to call Batumi
-Press "F1" to call Inbound
-Note the COMM 2 channel window on the iPad changes to **"\/"** during both transmissions instead of the in game symbol that resembles "<>". I assume this is due to iPad text imitations.
Initial bug seems resolved.

**Comment by wluc9875** [comment]
yes, I couldn't find the exact same symbol in the font I'm using.
