### ISSUE TITLE
JF17 - The blanked UFC buttons press UFC 0 instead of the respective blanked UFC button

### ISSUE THREAD

**Issue by asherao** [wluc9875/iUFCExport-iPad#44]
This maybe be a DCS issue too. This means I can't play my music via DPlayer via iUFCExport 😭 😆

**Comment by wluc9875** [comment]
it's because I thought they didn't have any use; I can easily activate them

**Comment by asherao** [comment]
Version 1.1(5)
The blanked buttons work, but are not animated in the iPad app.

**Comment by wluc9875** [comment]
will add these animations

**Comment by wluc9875** [comment]
animations added

**Comment by asherao** [comment]
Animations are working on the iPad, but there is some sort of black square near the center of the button when pressed. This occurs on the two right "UFCP Button N/A" blanked buttons. The black square looks like a leftover from a text mask for other buttons.

**Comment by asherao** [comment]
Black square is no longer present. Issue seems to be resolved.
