### ISSUE TITLE
Knobs do not display the current position in the app

### ISSUE THREAD

**Issue by asherao** [wluc9875/iUFCExport-iPad#49]

**Comment by wluc9875** [comment]
- rotaries (with discrete positions) already support it. Not visible in version 1 because I disabled the SA342 NADIR for now.
- 3-way switches, I'll try to support in version 1.1
- potentiometers (like COMM volume) are planned for later

**Comment by wluc9875** [comment]
closed in favour of more specific sync issues, like #36 or #42 
I don't intend to sync each and every possible buttons, but only latched ones (e.g. 3-way, rotaries)
