### ISSUE TITLE
JF 17 - issue with touchable zones for fast select switch

### ISSUE THREAD

**Issue by wluc9875** [wluc9875/iUFCExport-iPad#54]
(created from #45)
Touchable zone seems to have been extended. But there is a small area very close to the edge of the iPad, in between the edge of the iPad and the end of the lower clickable zone. Touching in this odd zone will not make a sound, but releasing will. There is no animation associated. Finger is not moved to or from another location on the iPad.

**Comment by wluc9875** [comment]
Unfortunately, I'm unable to reproduce this issue on the Xcode simulator for iPad Air 2 and I don't have this physical device.
I'll have to postpone this fix until I can reproduce.

**Comment by asherao** [comment]
After some examination, I believe that this bug is due to a reserved number of pixels at the bottom of the screen that are used to show the drag up bar. I believe there is no bug here. I have ben able to replicate the issue on the F18.
No bug.

**Comment by wluc9875** [comment]
thanks for analysing and finding the root cause!
In that case, I'll close this issue
