### ISSUE TITLE
A10C - Master Caution button does not work on iPad

### ISSUE THREAD

**Issue by asherao** [wluc9875/iUFCExport-iPad#57]
When pressed on the iPad, it seems that the Master Caution on the A10C UFC is not animated.

**Comment by asherao** [comment]
Title changed because when the button is pressed on the iPad, it does not animate on the iPad or in-game.

**Comment by asherao** [comment]
When pressed on the iPad, the iPad button depresses and so does the one ingame. 
I have not yet tested if the iPad button lights up during an ingame Master Caution event.

**Comment by wluc9875** [comment]
Thanks! you can check the light by shutting off one of the A10C engines for example.
